; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0L@OICGFOEL@output?4bmp?$AA@		; `string'
PUBLIC	??_C@_0P@NDNGIGNK@Teszt?5started?6?$AA@		; `string'
PUBLIC	??_C@_0BM@BNCOCNFJ@Output?5resolution?3?5?$CF4dx?$CF4d?6?$AA@ ; `string'
PUBLIC	??_C@_0BC@GIOFBGHC@hf_output_ref?4bmp?$AA@	; `string'
PUBLIC	??_C@_0CB@IAMBGCGL@Ref?5picture?5resolution?3?5?$CF4dx?$CF4d?6@ ; `string'
PUBLIC	??_C@_0BM@BOHMLGCJ@Nem?5egyeznek?5a?5sz?iless?igek?6?$AA@ ; `string'
PUBLIC	??_C@_0BM@IIPHDHFB@Nem?5egyeznek?5a?5hossz?zs?agok?6?$AA@ ; `string'
PUBLIC	??_C@_09CCAEKEFA@Baj?5van?$CB?6?$AA@		; `string'
PUBLIC	??_C@_07BLFELHIC@Erdeti?6?$AA@			; `string'
PUBLIC	??_C@_0BM@GEKJLJJG@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?5?$AA@ ; `string'
PUBLIC	??_C@_06EKAJNINI@Sajat?6?$AA@			; `string'
PUBLIC	??_C@_0BN@LJFGHIFM@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?6?5?$AA@ ; `string'
PUBLIC	??_C@_0M@CAGJMMDC@Minden?5ok?i?6?$AA@		; `string'
PUBLIC	??_C@_09HDLCNAPM@input?4jpg?$AA@		; `string'
PUBLIC	??_C@_0BL@EIJCCJGD@Input?5resolution?3?5?$CF4dx?$CF4d?6?$AA@ ; `string'
PUBLIC	??_C@_0BD@NGKMKCMP@C?5CPU?5TIME?3?5?$CF4?44f?6?$AA@ ; `string'
PUBLIC	??_C@_0BD@CKJPLJHO@C?5Mpixel?1s?3?5?$CF4?44f?6?$AA@ ; `string'
EXTRN	__imp_ilGenImages:PROC
EXTRN	__imp_ilGetInteger:PROC
EXTRN	__imp_ilGetData:PROC
EXTRN	__imp_ilBindImage:PROC
EXTRN	__imp_ilInit:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	__imp_iluInit:PROC
EXTRN	_aligned_malloc:PROC
EXTRN	__imp_ilDeleteImages:PROC
EXTRN	__imp_ilLoadImage:PROC
EXTRN	__acrt_iob_func:PROC
EXTRN	__imp_ilSetData:PROC
EXTRN	__imp_ilEnable:PROC
EXTRN	__imp_ilSaveImage:PROC
EXTRN	clock:PROC
EXTRN	_aligned_free:PROC
;	COMDAT ??_C@_0BD@CKJPLJHO@C?5Mpixel?1s?3?5?$CF4?44f?6?$AA@
CONST	SEGMENT
??_C@_0BD@CKJPLJHO@C?5Mpixel?1s?3?5?$CF4?44f?6?$AA@ DB 'C Mpixel/s: %4.4f'
	DB	0aH, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@NGKMKCMP@C?5CPU?5TIME?3?5?$CF4?44f?6?$AA@
CONST	SEGMENT
??_C@_0BD@NGKMKCMP@C?5CPU?5TIME?3?5?$CF4?44f?6?$AA@ DB 'C CPU TIME: %4.4f'
	DB	0aH, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@EIJCCJGD@Input?5resolution?3?5?$CF4dx?$CF4d?6?$AA@
CONST	SEGMENT
??_C@_0BL@EIJCCJGD@Input?5resolution?3?5?$CF4dx?$CF4d?6?$AA@ DB 'Input re'
	DB	'solution: %4dx%4d', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_09HDLCNAPM@input?4jpg?$AA@
CONST	SEGMENT
??_C@_09HDLCNAPM@input?4jpg?$AA@ DB 'input.jpg', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0M@CAGJMMDC@Minden?5ok?i?6?$AA@
CONST	SEGMENT
??_C@_0M@CAGJMMDC@Minden?5ok?i?6?$AA@ DB 'Minden ok', 0e9H, 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@LJFGHIFM@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?6?5?$AA@
CONST	SEGMENT
??_C@_0BN@LJFGHIFM@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?6?5?$AA@ DB '%'
	DB	'd. Sor, :%d. oszlop: %d ', 0aH, 0aH, ' ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_06EKAJNINI@Sajat?6?$AA@
CONST	SEGMENT
??_C@_06EKAJNINI@Sajat?6?$AA@ DB 'Sajat', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@GEKJLJJG@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?5?$AA@
CONST	SEGMENT
??_C@_0BM@GEKJLJJG@?$CFd?4?5Sor?0?5?3?$CFd?4?5oszlop?3?5?$CFd?5?6?5?$AA@ DB '%'
	DB	'd. Sor, :%d. oszlop: %d ', 0aH, ' ', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_07BLFELHIC@Erdeti?6?$AA@
CONST	SEGMENT
??_C@_07BLFELHIC@Erdeti?6?$AA@ DB 'Erdeti', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_09CCAEKEFA@Baj?5van?$CB?6?$AA@
CONST	SEGMENT
??_C@_09CCAEKEFA@Baj?5van?$CB?6?$AA@ DB 'Baj van!', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@IIPHDHFB@Nem?5egyeznek?5a?5hossz?zs?agok?6?$AA@
CONST	SEGMENT
??_C@_0BM@IIPHDHFB@Nem?5egyeznek?5a?5hossz?zs?agok?6?$AA@ DB 'Nem egyezne'
	DB	'k a hossz', 0faH, 's', 0e1H, 'gok', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@BOHMLGCJ@Nem?5egyeznek?5a?5sz?iless?igek?6?$AA@
CONST	SEGMENT
??_C@_0BM@BOHMLGCJ@Nem?5egyeznek?5a?5sz?iless?igek?6?$AA@ DB 'Nem egyezne'
	DB	'k a sz', 0e9H, 'less', 0e9H, 'gek', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@IAMBGCGL@Ref?5picture?5resolution?3?5?$CF4dx?$CF4d?6@
CONST	SEGMENT
??_C@_0CB@IAMBGCGL@Ref?5picture?5resolution?3?5?$CF4dx?$CF4d?6@ DB 'Ref p'
	DB	'icture resolution: %4dx%4d', 0aH, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BC@GIOFBGHC@hf_output_ref?4bmp?$AA@
CONST	SEGMENT
??_C@_0BC@GIOFBGHC@hf_output_ref?4bmp?$AA@ DB 'hf_output_ref.bmp', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@BNCOCNFJ@Output?5resolution?3?5?$CF4dx?$CF4d?6?$AA@
CONST	SEGMENT
??_C@_0BM@BNCOCNFJ@Output?5resolution?3?5?$CF4dx?$CF4d?6?$AA@ DB 'Output '
	DB	'resolution: %4dx%4d', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@NDNGIGNK@Teszt?5started?6?$AA@
CONST	SEGMENT
??_C@_0P@NDNGIGNK@Teszt?5started?6?$AA@ DB 'Teszt started', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@OICGFOEL@output?4bmp?$AA@
CONST	SEGMENT
??_C@_0L@OICGFOEL@output?4bmp?$AA@ DB 'output.bmp', 00H	; `string'
CONST	ENDS
PUBLIC	main
PUBLIC	?verifyImage@@YAHXZ				; verifyImage
PUBLIC	printf
PUBLIC	_vfprintf_l
PUBLIC	__local_stdio_printf_options
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN102
	DD	imagerel $LN102+37
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$main DD imagerel $LN102+37
	DD	imagerel $LN102+298
	DD	imagerel $chain$0$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$main DD imagerel $LN102+298
	DD	imagerel $LN102+1621
	DD	imagerel $chain$2$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$main DD imagerel $LN102+1621
	DD	imagerel $LN102+2463
	DD	imagerel $chain$3$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?verifyImage@@YAHXZ DD imagerel $LN22@verifyImag
	DD	imagerel $LN22@verifyImag+334
	DD	imagerel $unwind$?verifyImage@@YAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?verifyImage@@YAHXZ DD imagerel $LN22@verifyImag+334
	DD	imagerel $LN22@verifyImag+350
	DD	imagerel $chain$0$?verifyImage@@YAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?verifyImage@@YAHXZ DD imagerel $LN22@verifyImag+350
	DD	imagerel $LN22@verifyImag+539
	DD	imagerel $chain$2$?verifyImage@@YAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?verifyImage@@YAHXZ DD imagerel $LN22@verifyImag+539
	DD	imagerel $LN22@verifyImag+603
	DD	imagerel $chain$3$?verifyImage@@YAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN6@printf
	DD	imagerel $LN6@printf+83
	DD	imagerel $unwind$printf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4@vfprintf_l
	DD	imagerel $LN4@vfprintf_l+67
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 060f01H
	DD	09640fH
	DD	08340fH
	DD	0700b520fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 041b01H
	DD	07017521bH
	DD	030156016H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?verifyImage@@YAHXZ DD 021H
	DD	imagerel $LN22@verifyImag+334
	DD	imagerel $LN22@verifyImag+350
	DD	imagerel $chain$0$?verifyImage@@YAHXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?verifyImage@@YAHXZ DD 040e21H
	DD	05d40eH
	DD	075405H
	DD	imagerel $LN22@verifyImag+334
	DD	imagerel $LN22@verifyImag+350
	DD	imagerel $chain$0$?verifyImage@@YAHXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?verifyImage@@YAHXZ DD 020521H
	DD	066405H
	DD	imagerel $LN22@verifyImag
	DD	imagerel $LN22@verifyImag+334
	DD	imagerel $unwind$?verifyImage@@YAHXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?verifyImage@@YAHXZ DD 060d01H
	DD	0f009720dH
	DD	0c005e007H
	DD	030027003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$main DD 040021H
	DD	031e400H
	DD	030d400H
	DD	imagerel $LN102
	DD	imagerel $LN102+37
	DD	imagerel $unwind$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$main DD 041021H
	DD	031e410H
	DD	030d408H
	DD	imagerel $LN102+37
	DD	imagerel $LN102+298
	DD	imagerel $chain$0$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$main DD 020921H
	DD	0146809H
	DD	imagerel $LN102
	DD	imagerel $LN102+37
	DD	imagerel $unwind$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	092519H
	DD	0323413H
	DD	02a0113H
	DD	0c00af00cH
	DD	060077008H
	DD	05006H
	DD	imagerel __GSHandlerCheck
	DD	0130H
; Function compile flags: /Ogtpy
; File d:\d_strabi\d dokumentumai\bme\heterogén számítási rendszerek\hf\kismacska\hetero_hf_3\heterogen_hf_cpu_batchers\heterogen_hf_szp\_src\main.cpp
; File d:\d_strabi\d dokumentumai\bme\heterogén számítási rendszerek\hf\kismacska\hetero_hf_3\heterogen_hf_cpu_batchers\heterogen_hf_szp\_src\conv_filter.cpp
; File d:\d_strabi\d dokumentumai\bme\heterogén számítási rendszerek\hf\kismacska\hetero_hf_3\heterogen_hf_cpu_batchers\heterogen_hf_szp\_src\main.cpp
;	COMDAT main
_TEXT	SEGMENT
imgWidth$1$ = 32
tv13713 = 36
s0$1$ = 36
imgWidthF$1$ = 36
tv13778 = 40
tv13733 = 40
tv13775 = 48
tv13741 = 48
tv13724 = 48
tv13774 = 56
tv13743 = 56
tv13729 = 56
tv13734 = 64
imgHeight$1$ = 64
ilImg$ = 72
tv13777 = 80
imgFloatRes$1$ = 80
imgData$1$ = 88
tv13730 = 96
tv13718 = 96
tv13837 = 104
tv13761 = 104
tv13759 = 112
tv13721 = 112
tv13756 = 120
tv13690 = 120
tv13744 = 128
tv13688 = 128
tv13797 = 136
tv13692 = 136
tv13795 = 144
tv13694 = 144
tv13757 = 152
tv13698 = 152
tv13801 = 160
tv13700 = 160
imgFloat$1$ = 168
tv13763 = 176
medianArray$1 = 192
__$ArrayPad$ = 304
main	PROC						; COMDAT

; 102  : {

$LN102:
	mov	QWORD PTR [rsp+24], rbx
	push	rbp
	push	rsi
	push	rdi
	push	r12
	push	r15
	sub	rsp, 336				; 00000150H
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rsp
	mov	QWORD PTR __$ArrayPad$[rsp], rax
	vmovaps	XMMWORD PTR [rsp+320], xmm6

; 103  : #ifdef  VERIFY
; 104  : 
; 105  : 	verifyImage();
; 106  : #else 
; 107  : 	ilInit(); iluInit();

	call	QWORD PTR __imp_ilInit
	call	QWORD PTR __imp_iluInit

; 108  : 	ILboolean ret;
; 109  : 	ILuint ilImg=0;

	xor	r12d, r12d

; 110  : 	ilGenImages(1, &ilImg);

	lea	rdx, QWORD PTR ilImg$[rsp]
	mov	DWORD PTR ilImg$[rsp], r12d
	lea	ecx, QWORD PTR [r12+1]
	call	QWORD PTR __imp_ilGenImages

; 111  : 	ilBindImage(ilImg);

	mov	ecx, DWORD PTR ilImg$[rsp]
	call	QWORD PTR __imp_ilBindImage

; 112  :     ret = ilLoadImage((const char*)("input.jpg"));

	lea	rcx, OFFSET FLAT:??_C@_09HDLCNAPM@input?4jpg?$AA@
	call	QWORD PTR __imp_ilLoadImage

; 113  : 	ILubyte* imgData = ilGetData(); 

	call	QWORD PTR __imp_ilGetData

; 114  : 
; 115  : 	int imgWidth = ilGetInteger(IL_IMAGE_WIDTH);

	mov	ecx, 3556				; 00000de4H
	mov	QWORD PTR imgData$1$[rsp], rax
	call	QWORD PTR __imp_ilGetInteger

; 116  : 	int imgHeight = ilGetInteger(IL_IMAGE_HEIGHT);

	mov	ecx, 3557				; 00000de5H
	mov	DWORD PTR imgWidth$1$[rsp], eax
	mov	r15d, eax
	call	QWORD PTR __imp_ilGetInteger

; 117  : 	ILint imgOrigin = ilGetInteger(IL_ORIGIN_MODE);

	mov	ecx, 1539				; 00000603H
	mov	DWORD PTR imgHeight$1$[rsp], eax
	mov	ebp, eax
	call	QWORD PTR __imp_ilGetInteger

; 118  : 
; 119  : 	printf("Input resolution: %4dx%4d\n", imgWidth, imgHeight);

	mov	r8d, ebp
	lea	rcx, OFFSET FLAT:??_C@_0BL@EIJCCJGD@Input?5resolution?3?5?$CF4dx?$CF4d?6?$AA@
	mov	edx, r15d
	call	printf

; 120  : 
; 121  : 	float *imgFloat;
; 122  : 	int imgWidthF = imgWidth+FILTER_W-1;

	lea	esi, DWORD PTR [r15+4]

; 123  : 	int imgHeightF = imgHeight+FILTER_H-1;

	lea	edi, DWORD PTR [rbp+4]
	mov	DWORD PTR imgWidthF$1$[rsp], esi

; 124  : 	int imgFOffsetW = (FILTER_W-1)/2;
; 125  : 	int imgFOffsetH = (FILTER_H-1)/2;
; 126  : 	imgFloat   = (float *)(_aligned_malloc(4*imgWidthF*imgHeightF*sizeof(float), 32));

	mov	eax, edi
	lea	edx, QWORD PTR [r12+32]
	imul	eax, esi
	shl	eax, 2
	cdqe
	shl	rax, 2
	mov	rcx, rax
	mov	QWORD PTR tv13801[rsp], rax
	call	_aligned_malloc
	mov	QWORD PTR imgFloat$1$[rsp], rax
	mov	rbx, rax

; 127  :     int row, col;
; 128  : 
; 129  : 	for (row=0; row<imgHeightF; row++)

	test	edi, edi
	jle	SHORT $LN3@main

; 103  : #ifdef  VERIFY
; 104  : 
; 105  : 	verifyImage();
; 106  : #else 
; 107  : 	ilInit(); iluInit();

	lea	ecx, DWORD PTR [rsi*4]
	mov	r8d, edi
	movsxd	r9, ecx
	lea	rdx, QWORD PTR [rax+8]
	shl	r9, 2
$LL4@main:

; 130  : 	{
; 131  : 		for (col=0; col<imgWidthF;col++)

	test	esi, esi
	jle	SHORT $LN2@main
	mov	rax, rdx
	mov	ecx, esi
	npad	1
$LL7@main:

; 132  : 		{
; 133  : 			int pixel = (row*imgWidthF + col)*4;
; 134  : 			*(imgFloat+pixel+0) = 0.0f;

	mov	QWORD PTR [rax-8], r12

; 135  : 			*(imgFloat + pixel + 1) = 0.0f;
; 136  : 			*(imgFloat + pixel + 2) = 0.0f;

	mov	QWORD PTR [rax], r12
	lea	rax, QWORD PTR [rax+16]
	sub	rcx, 1
	jne	SHORT $LL7@main
$LN2@main:

; 127  :     int row, col;
; 128  : 
; 129  : 	for (row=0; row<imgHeightF; row++)

	add	rdx, r9
	sub	r8, 1
	jne	SHORT $LL4@main
$LN3@main:
	mov	QWORD PTR [rsp+384], r13
	mov	QWORD PTR [rsp+392], r14

; 137  : 			*(imgFloat + pixel + 3) = 0.0f;
; 138  : 		}
; 139  : 	}
; 140  : 
; 141  : 	for (row=0; row<imgHeight; row++)

	test	ebp, ebp
	jle	$LN9@main
	mov	r8d, DWORD PTR imgWidth$1$[rsp]
	lea	ecx, DWORD PTR [rsi*8]
	mov	r14d, r12d
	movsxd	rbp, ecx
	add	rbp, 8
	lea	r15d, DWORD PTR [rsi+rsi]
	mov	rdi, r12
	mov	DWORD PTR tv13778[rsp], r15d
	lea	eax, DWORD PTR [r8+r8*2]
	movsxd	r12, ecx
	cdqe
	mov	QWORD PTR tv13757[rsp], rax
	lea	r13, QWORD PTR [rbp+6]
	lea	eax, DWORD PTR [rsi*4]
	mov	QWORD PTR tv13775[rsp], rbp
	cdqe
	lea	r13, QWORD PTR [rbx+r13*4]
	mov	QWORD PTR tv13797[rsp], rax
	mov	QWORD PTR tv13774[rsp], r13
	lea	rax, QWORD PTR [rax*4]
	mov	QWORD PTR tv13795[rsp], rax
	lea	eax, DWORD PTR [rsi*8+16]
	movsxd	rdx, eax
	mov	eax, DWORD PTR imgHeight$1$[rsp]
	sub	rdx, rbp
	mov	QWORD PTR tv13718[rsp], rdx
	sub	r12, rbp
	mov	QWORD PTR tv13777[rsp], rax
	npad	10
$LL10@main:

; 142  : 	{
; 143  : 		for (col=0; col<imgWidth;col++)

	xor	r11d, r11d
	cmp	r8d, 4
	jl	$LC82@main
	mov	rbx, QWORD PTR imgData$1$[rsp]
	lea	rcx, QWORD PTR [rdi+9]
	mov	rax, rcx
	mov	r10, rbx
	sub	rax, rdi
	sub	rcx, rdi
	add	rax, -3
	mov	r8, r13
	mov	QWORD PTR tv13763[rsp], rax
	lea	rdx, QWORD PTR [rbx+1]
	sub	rax, rdx
	lea	r11, QWORD PTR [rbx-3]
	add	r11, rax
	lea	r9, QWORD PTR [rdx+3]
	dec	rax
	mov	QWORD PTR tv13761[rsp], r11
	mov	rsi, QWORD PTR tv13761[rsp]
	add	rax, rbx
	mov	QWORD PTR tv13759[rsp], rax
	sub	rcx, rdx
	mov	rbp, QWORD PTR tv13759[rsp]
	sub	r10, rdx
	mov	rdx, QWORD PTR tv13718[rsp]
	add	r9, rdi
	lea	rax, QWORD PTR [rcx+rbx]
	mov	QWORD PTR tv13690[rsp], rax
	lea	rax, QWORD PTR [rbx+2]
	mov	rbx, QWORD PTR tv13763[rsp]
	add	rax, rcx
	mov	r15, QWORD PTR tv13690[rsp]
	mov	QWORD PTR tv13688[rsp], rax
	mov	eax, DWORD PTR imgWidth$1$[rsp]
	mov	r13, QWORD PTR tv13688[rsp]
	add	eax, -4					; fffffffcH
	shr	eax, 2
	inc	eax
	mov	ecx, eax
	lea	r11d, DWORD PTR [rax*4]
	npad	2
$LL83@main:

; 144  : 		{
; 145  : 			int pixel_dst = ((row+imgFOffsetH)*imgWidthF + (col+imgFOffsetW))*4;
; 146  : 			int pixel_src = (row*imgWidth + col)*3;
; 147  : 			*(imgFloat+pixel_dst+0) = (float)(*(imgData+pixel_src+0));

	movzx	eax, BYTE PTR [r9+r10-3]

; 150  : 			*(imgFloat+pixel_dst+3) = 0.0;

	lea	r8, QWORD PTR [r8+64]
	lea	r9, QWORD PTR [r9+12]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-88], xmm0
	movzx	eax, BYTE PTR [r9-15]
	vxorps	xmm0, xmm0, xmm0
	vxorps	xmm1, xmm1, xmm1
	vcvtsi2ss xmm1, xmm1, eax
	vmovss	DWORD PTR [r8-84], xmm1
	movzx	eax, BYTE PTR [r9-14]
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-80], xmm0
	mov	DWORD PTR [r8-76], 0
	movzx	eax, BYTE PTR [r9+r10-12]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-72], xmm0
	movzx	eax, BYTE PTR [r9-12]
	vxorps	xmm0, xmm0, xmm0
	vxorps	xmm1, xmm1, xmm1
	vcvtsi2ss xmm1, xmm1, eax
	vmovss	DWORD PTR [r8-68], xmm1
	movzx	eax, BYTE PTR [r9-11]
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-64], xmm0
	mov	DWORD PTR [r8-60], 0
	movzx	eax, BYTE PTR [r9+rsi-12]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8+rdx*4-88], xmm0
	movzx	eax, BYTE PTR [r9+rbx-15]
	vxorps	xmm0, xmm0, xmm0
	vxorps	xmm1, xmm1, xmm1
	vcvtsi2ss xmm1, xmm1, eax
	vmovss	DWORD PTR [r8+rdx*4-84], xmm1
	movzx	eax, BYTE PTR [r9+rbp-12]
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8+rdx*4-80], xmm0
	mov	DWORD PTR [r8+rdx*4-76], 0
	movzx	eax, BYTE PTR [r15+r9-15]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8+r12*4-8], xmm0
	movzx	eax, BYTE PTR [r9-6]
	vxorps	xmm1, xmm1, xmm1
	vcvtsi2ss xmm1, xmm1, eax
	vmovss	DWORD PTR [r8+r12*4-4], xmm1
	movzx	eax, BYTE PTR [r9+r13-15]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8+r12*4], xmm0
	mov	DWORD PTR [r8+r12*4+4], 0
	sub	rcx, 1
	jne	$LL83@main
	mov	rbx, QWORD PTR imgFloat$1$[rsp]
	mov	esi, DWORD PTR imgWidthF$1$[rsp]
	mov	rbp, QWORD PTR tv13775[rsp]
	mov	r15d, DWORD PTR tv13778[rsp]
	mov	r13, QWORD PTR tv13774[rsp]
	mov	rax, QWORD PTR tv13777[rsp]
	mov	r8d, DWORD PTR imgWidth$1$[rsp]
$LC82@main:

; 142  : 	{
; 143  : 		for (col=0; col<imgWidth;col++)

	cmp	r11d, r8d
	jge	$LN8@main
	mov	r10, QWORD PTR imgData$1$[rsp]
	lea	eax, DWORD PTR [r14+r11]
	lea	ecx, DWORD PTR [rax+rax*2]
	movsxd	r9, ecx
	lea	eax, DWORD PTR [r15+r11]
	mov	ecx, DWORD PTR imgWidth$1$[rsp]
	lea	eax, DWORD PTR [rax*4+8]
	lea	rdx, QWORD PTR [r10+1]
	movsxd	r8, eax
	add	r8, 2
	add	r9, rdx
	sub	r10, rdx
	sub	ecx, r11d
	lea	r8, QWORD PTR [rbx+r8*4]
$LC13@main:

; 144  : 		{
; 145  : 			int pixel_dst = ((row+imgFOffsetH)*imgWidthF + (col+imgFOffsetW))*4;
; 146  : 			int pixel_src = (row*imgWidth + col)*3;
; 147  : 			*(imgFloat+pixel_dst+0) = (float)(*(imgData+pixel_src+0));

	movzx	eax, BYTE PTR [r9+r10]
	lea	r8, QWORD PTR [r8+16]
	lea	r9, QWORD PTR [r9+3]
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-24], xmm0

; 148  : 			*(imgFloat+pixel_dst+1) = (float)(*(imgData+pixel_src+1));

	movzx	eax, BYTE PTR [r9-3]
	vxorps	xmm1, xmm1, xmm1
	vcvtsi2ss xmm1, xmm1, eax
	vmovss	DWORD PTR [r8-20], xmm1

; 149  : 			*(imgFloat+pixel_dst+2) = (float)(*(imgData+pixel_src+2));

	movzx	eax, BYTE PTR [r9-2]

; 150  : 			*(imgFloat+pixel_dst+3) = 0.0;

	mov	DWORD PTR [r8-12], 0
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2ss xmm0, xmm0, eax
	vmovss	DWORD PTR [r8-16], xmm0
	sub	rcx, 1
	jne	SHORT $LC13@main
	mov	rax, QWORD PTR tv13777[rsp]
	mov	r8d, DWORD PTR imgWidth$1$[rsp]
$LN8@main:

; 137  : 			*(imgFloat + pixel + 3) = 0.0f;
; 138  : 		}
; 139  : 	}
; 140  : 
; 141  : 	for (row=0; row<imgHeight; row++)

	add	rbp, QWORD PTR tv13797[rsp]
	add	r15d, esi
	add	r13, QWORD PTR tv13795[rsp]
	add	r14d, r8d
	add	rdi, QWORD PTR tv13757[rsp]
	sub	rax, 1
	mov	QWORD PTR tv13775[rsp], rbp
	mov	QWORD PTR tv13777[rsp], rax
	mov	QWORD PTR tv13774[rsp], r13
	mov	DWORD PTR tv13778[rsp], r15d
	jne	$LL10@main
	mov	r15d, DWORD PTR imgWidth$1$[rsp]
	mov	ebp, DWORD PTR imgHeight$1$[rsp]
$LN9@main:

; 151  : 		}
; 152  : 	}
; 153  : 
; 154  : 
; 155  : // IMAGE PROCESSING
; 156  : //---------------------------------------------------------------------------------------
; 157  : 	clock_t s0, e0;
; 158  :     double d0;
; 159  : 
; 160  : 	float *imgFloatRes;
; 161  :     imgFloatRes = (float *)(_aligned_malloc(4*imgWidthF*imgHeightF*sizeof(float), 32));

	mov	rcx, QWORD PTR tv13801[rsp]
	mov	edx, 32					; 00000020H
	call	_aligned_malloc
	mov	rdi, rax
	mov	QWORD PTR imgFloatRes$1$[rsp], rax

; 162  : 
; 163  : 	double mpixel;
; 164  : 
; 165  : 
; 166  : 	s0 = clock();

	call	clock
	mov	DWORD PTR s0$1$[rsp], eax
	lea	eax, DWORD PTR [rbp+2]
; File d:\d_strabi\d dokumentumai\bme\heterogén számítási rendszerek\hf\kismacska\hetero_hf_3\heterogen_hf_cpu_batchers\heterogen_hf_szp\_src\conv_filter.cpp

; 383  : 	for (int y=imgFOffsetH; y<(imgHeight + imgFOffsetH); y++)

	cmp	eax, 2
	jle	$LN14@main
	lea	ecx, DWORD PTR [r15*4]
	mov	r12d, 8
	movsxd	rcx, ecx
	lea	r8d, DWORD PTR [r15+2]
	shl	rcx, 2
	lea	esi, DWORD PTR [rsi*4]
	mov	QWORD PTR tv13743[rsp], rcx
	add	eax, -2					; fffffffeH
	lea	ecx, DWORD PTR [r15*8+8]
	mov	QWORD PTR tv13741[rsp], rax
	movsxd	rdx, ecx
	mov	rcx, QWORD PTR tv13743[rsp]
	lea	r13, QWORD PTR [rdi+rdx*4]
$LL27@main:

; 384  : 		// KÃ©p oszlopai
; 385  : 		for (int x=imgFOffsetW; x<(imgWidth + imgFOffsetW); x++)

	cmp	r8d, 2
	jle	$LN25@main
	mov	r14d, r12d
	lea	ebp, DWORD PTR [r8-2]
	mov	rdi, r13
	npad	6
$LL30@main:

; 386  : 			// SzÃ­n komponensek
; 387  : 			for (int rgb = 0; rgb < 4; rgb++)

	xor	r10d, r10d
	npad	13
$LL33@main:

; 388  : 			{			
; 389  : 				float medianArray[25];
; 390  : 
; 391  : 				for (int medianY = 0; medianY < 5; medianY++) 

	lea	rdx, QWORD PTR medianArray$1[rsp+4]
	mov	r9d, 5
	lea	r8d, DWORD PTR [r14+r10]
$LL36@main:

; 392  : 					for (int medianX = 0; medianX < 5; medianX++) 
; 393  : 						medianArray[5*medianY  + medianX] = imgFloatSrc[((y+(medianY-2))*imgWidthF + x + (medianX-2))*4 + rgb];

	movsxd	rax, r8d
	lea	rdx, QWORD PTR [rdx+20]
	mov	ecx, DWORD PTR [rbx+rax*4-32]
	mov	DWORD PTR [rdx-24], ecx
	movsxd	rcx, r8d
	mov	eax, DWORD PTR [rbx+rcx*4-16]
	mov	DWORD PTR [rdx-20], eax
	mov	eax, DWORD PTR [rbx+rcx*4]
	mov	DWORD PTR [rdx-16], eax
	mov	eax, DWORD PTR [rbx+rcx*4+16]
	mov	DWORD PTR [rdx-12], eax
	movsxd	rax, r8d
	add	r8d, esi
	mov	ecx, DWORD PTR [rbx+rax*4+32]
	mov	DWORD PTR [rdx-8], ecx
	sub	r9, 1
	jne	SHORT $LL36@main

; 394  : 
; 395  : 				mergeSort(medianArray);

	lea	rcx, QWORD PTR medianArray$1[rsp]
	call	?mergeSort@@YAXPEAM@Z			; mergeSort

; 396  : 				//mergeSortFull(medianArray);
; 397  : 				imgFloatDst[(y*imgWidth + x) * 4 + rgb] = medianArray[MEDIAN];

	vmovss	xmm0, DWORD PTR medianArray$1[rsp+48]
	vmovss	DWORD PTR [rdi], xmm0
	add	rdi, 4
	inc	r10d
	cmp	r10d, 4
	jl	SHORT $LL33@main

; 384  : 		// KÃ©p oszlopai
; 385  : 		for (int x=imgFOffsetW; x<(imgWidth + imgFOffsetW); x++)

	add	r14d, 4
	sub	rbp, 1
	jne	$LL30@main
	mov	rax, QWORD PTR tv13741[rsp]
	lea	r8d, DWORD PTR [r15+2]
	mov	rcx, QWORD PTR tv13743[rsp]
$LN25@main:

; 383  : 	for (int y=imgFOffsetH; y<(imgHeight + imgFOffsetH); y++)

	add	r12d, esi
	add	r13, rcx
	sub	rax, 1
	mov	QWORD PTR tv13741[rsp], rax
	jne	$LL27@main
	mov	rdi, QWORD PTR imgFloatRes$1$[rsp]
	mov	ebp, DWORD PTR imgHeight$1$[rsp]
$LN14@main:
; File d:\d_strabi\d dokumentumai\bme\heterogén számítási rendszerek\hf\kismacska\hetero_hf_3\heterogen_hf_cpu_batchers\heterogen_hf_szp\_src\main.cpp

; 174  :     e0 = clock();

	call	clock

; 175  :     d0 = (double)(e0-s0)/(RUNS*CLOCKS_PER_SEC);

	sub	eax, DWORD PTR s0$1$[rsp]

; 176  : 	mpixel = (imgWidth*imgHeight/d0)/1000000;
; 177  :     printf("C CPU TIME: %4.4f\n", d0);

	lea	rcx, OFFSET FLAT:??_C@_0BD@NGKMKCMP@C?5CPU?5TIME?3?5?$CF4?44f?6?$AA@
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2sd xmm0, xmm0, eax
	vdivsd	xmm6, xmm0, QWORD PTR __real@408f400000000000
	vmovaps	xmm1, xmm6
	vmovq	rdx, xmm1
	call	printf
	mov	eax, ebp

; 178  : 	printf("C Mpixel/s: %4.4f\n", mpixel);

	lea	rcx, OFFSET FLAT:??_C@_0BD@CKJPLJHO@C?5Mpixel?1s?3?5?$CF4?44f?6?$AA@
	imul	eax, r15d
	vxorps	xmm0, xmm0, xmm0
	vcvtsi2sd xmm0, xmm0, eax
	vdivsd	xmm1, xmm0, xmm6
	vdivsd	xmm1, xmm1, QWORD PTR __real@412e848000000000
	vmovq	rdx, xmm1
	call	printf
	vmovaps	xmm6, XMMWORD PTR [rsp+320]

; 179  : 
; 180  : 
; 181  : 
; 182  : 	float *imgFloatWrite;
; 183  : 	imgFloatWrite = imgFloatRes;
; 184  : 
; 185  : //---------------------------------------------------------------------------------------
; 186  : // IMAGE PROCESSING END
; 187  : 
; 188  : 
; 189  : 	for (row=0; row<imgHeight; row++)

	test	ebp, ebp
	jle	$LN18@main

; 175  :     d0 = (double)(e0-s0)/(RUNS*CLOCKS_PER_SEC);

	mov	edx, DWORD PTR imgWidth$1$[rsp]
	lea	eax, DWORD PTR [r15+r15*2]
	mov	esi, DWORD PTR imgHeight$1$[rsp]
	lea	ecx, DWORD PTR [r15*8]
	movsxd	r12, eax
	xor	r14d, r14d
	lea	eax, DWORD PTR [r15*4]
	movsxd	rbp, ecx
	add	rbp, 8
	movsxd	r15, eax
	xor	r13d, r13d
	movsxd	r10, ecx
	lea	eax, DWORD PTR [rdx*8+16]
	movsxd	r11, ecx
	cdqe
	lea	r9d, DWORD PTR [rdx+rdx]
	sub	r10, rax
	mov	DWORD PTR tv13733[rsp], r14d
	sub	rax, rbp
	mov	QWORD PTR tv13730[rsp], r13
	lea	rbx, QWORD PTR [rbp+2]
	mov	QWORD PTR tv13721[rsp], rax
	lea	rbx, QWORD PTR [rdi+rbx*4]
	mov	QWORD PTR tv13756[rsp], r12
	mov	QWORD PTR tv13724[rsp], rbx
	sub	r11, rbp
	mov	QWORD PTR tv13729[rsp], rbp
	mov	QWORD PTR tv13744[rsp], r15
	mov	QWORD PTR tv13837[rsp], r10
	mov	DWORD PTR tv13713[rsp], r9d
	mov	QWORD PTR tv13734[rsp], rsi
	npad	3
$LL19@main:

; 190  : 	{
; 191  : 		for (col=0; col<imgWidth;col++)

	xor	edi, edi
	cmp	edx, 4
	jl	$LC85@main
	mov	r14, QWORD PTR imgData$1$[rsp]
	lea	r9, QWORD PTR [rax+rbp]
	lea	r15, QWORD PTR [r13+9]
	mov	rsi, r14
	mov	r12, r15
	mov	rax, r9
	sub	rax, rbp
	sub	r12, r13
	add	r10, rax
	lea	rcx, QWORD PTR [r14+1]
	lea	rdx, QWORD PTR [rcx+3]
	sub	rsi, rcx
	lea	rdi, QWORD PTR [r14-3]
	sub	r15, r13
	add	rdx, r13
	lea	rax, QWORD PTR [r12-3]
	sub	rax, rcx
	sub	r9, rbp
	add	rdi, rax
	mov	r8, rbx
	dec	rax
	mov	QWORD PTR tv13700[rsp], rdi
	mov	rbx, QWORD PTR tv13700[rsp]
	add	rax, r14
	mov	QWORD PTR tv13698[rsp], rax
	mov	rax, r15
	sub	rax, rcx
	lea	rcx, QWORD PTR [r14-3]
	add	rcx, rax
	dec	r14
	add	rax, r14
	mov	QWORD PTR tv13694[rsp], rcx
	mov	r14, QWORD PTR tv13698[rsp]
	mov	rbp, QWORD PTR tv13694[rsp]
	mov	QWORD PTR tv13692[rsp], rax
	mov	eax, DWORD PTR imgWidth$1$[rsp]
	mov	r13, QWORD PTR tv13692[rsp]
	add	eax, -4					; fffffffcH
	shr	eax, 2
	inc	eax
	mov	ecx, eax
	lea	edi, DWORD PTR [rax*4]
	npad	2
$LL86@main:

; 197  : 			*(imgData+pixel_dst+2) = (ILubyte)(*(imgFloatWrite+pixel_src+2));

	lea	rdx, QWORD PTR [rdx+12]
	vcvttss2si eax, DWORD PTR [r8-8]
	mov	BYTE PTR [rsi+rdx-15], al
	vcvttss2si eax, DWORD PTR [r8-4]
	mov	BYTE PTR [rdx-15], al
	vcvttss2si eax, DWORD PTR [r8]
	mov	BYTE PTR [rdx-14], al
	vcvttss2si eax, DWORD PTR [r8+r10*4+40]
	mov	BYTE PTR [rsi+rdx-12], al
	vcvttss2si eax, DWORD PTR [r8+r10*4+44]
	mov	BYTE PTR [rdx-12], al
	vcvttss2si eax, DWORD PTR [r8+r10*4+48]
	mov	BYTE PTR [rdx-11], al
	vcvttss2si eax, DWORD PTR [r8+r9*4-8]
	mov	BYTE PTR [rbx+rdx-12], al
	vcvttss2si eax, DWORD PTR [r8+r9*4-4]
	mov	BYTE PTR [r12+rdx-18], al
	vcvttss2si eax, DWORD PTR [r8+r9*4]
	mov	BYTE PTR [r14+rdx-12], al
	vcvttss2si eax, DWORD PTR [r8+r11*4+72]
	mov	BYTE PTR [rdx+rbp-12], al
	vcvttss2si eax, DWORD PTR [r8+r11*4+76]
	mov	BYTE PTR [r15+rdx-15], al
	vcvttss2si eax, DWORD PTR [r8+r11*4+80]
	mov	BYTE PTR [rdx+r13-12], al
	lea	r8, QWORD PTR [r8+64]
	sub	rcx, 1
	jne	$LL86@main
	mov	rbp, QWORD PTR tv13729[rsp]
	mov	r14d, DWORD PTR tv13733[rsp]
	mov	r13, QWORD PTR tv13730[rsp]
	mov	rbx, QWORD PTR tv13724[rsp]
	mov	rsi, QWORD PTR tv13734[rsp]
	mov	r15, QWORD PTR tv13744[rsp]
	mov	r12, QWORD PTR tv13756[rsp]
	mov	r9d, DWORD PTR tv13713[rsp]
	mov	edx, DWORD PTR imgWidth$1$[rsp]
$LC85@main:

; 190  : 	{
; 191  : 		for (col=0; col<imgWidth;col++)

	cmp	edi, edx
	jge	SHORT $LN17@main
	mov	r10, QWORD PTR imgData$1$[rsp]
	lea	eax, DWORD PTR [r14+rdi]
	lea	ecx, DWORD PTR [rax+rax*2]
	lea	eax, DWORD PTR [r9+r14]
	movsxd	r8, ecx
	add	eax, edi
	lea	rdx, QWORD PTR [r10+1]
	add	r8, rdx
	sub	r10, rdx
	mov	edx, DWORD PTR imgWidth$1$[rsp]
	mov	ecx, edx
	lea	eax, DWORD PTR [rax*4+8]
	movsxd	r9, eax
	mov	rax, QWORD PTR imgFloatRes$1$[rsp]
	add	rax, 8
	sub	ecx, edi
	lea	r9, QWORD PTR [rax+r9*4]
$LC22@main:
	lea	r8, QWORD PTR [r8+3]

; 192  : 		{
; 193  : 			int pixel_src = ((row+2)*imgWidth + col+2)*4;
; 194  : 			int pixel_dst = (row*imgWidth + col)*3;
; 195  : 			*(imgData+pixel_dst+0) = (ILubyte)(*(imgFloatWrite+pixel_src+0));

	vcvttss2si eax, DWORD PTR [r9-8]
	mov	BYTE PTR [r8+r10-3], al

; 196  : 			*(imgData+pixel_dst+1) = (ILubyte)(*(imgFloatWrite+pixel_src+1));

	vcvttss2si eax, DWORD PTR [r9-4]
	mov	BYTE PTR [r8-3], al

; 197  : 			*(imgData+pixel_dst+2) = (ILubyte)(*(imgFloatWrite+pixel_src+2));

	vcvttss2si eax, DWORD PTR [r9]
	mov	BYTE PTR [r8-2], al
	lea	r9, QWORD PTR [r9+16]
	sub	rcx, 1
	jne	SHORT $LC22@main
$LN17@main:

; 179  : 
; 180  : 
; 181  : 
; 182  : 	float *imgFloatWrite;
; 183  : 	imgFloatWrite = imgFloatRes;
; 184  : 
; 185  : //---------------------------------------------------------------------------------------
; 186  : // IMAGE PROCESSING END
; 187  : 
; 188  : 
; 189  : 	for (row=0; row<imgHeight; row++)

	mov	r9d, DWORD PTR tv13713[rsp]
	lea	rax, QWORD PTR [r15*4]
	mov	r10, QWORD PTR tv13837[rsp]
	add	rbx, rax
	mov	rax, QWORD PTR tv13721[rsp]
	add	r14d, edx
	add	rbp, r15
	mov	DWORD PTR tv13733[rsp], r14d
	add	r13, r12
	mov	QWORD PTR tv13729[rsp], rbp
	sub	rsi, 1
	mov	QWORD PTR tv13724[rsp], rbx
	mov	QWORD PTR tv13734[rsp], rsi
	mov	QWORD PTR tv13730[rsp], r13
	jne	$LL19@main
	mov	rbx, QWORD PTR imgFloat$1$[rsp]
$LN18@main:

; 198  : 		}
; 199  : 	}
; 200  : 
; 201  : 
; 202  : 	_aligned_free(imgFloat);

	mov	rcx, rbx
	call	_aligned_free

; 203  :     _aligned_free(imgFloatRes);

	mov	rcx, QWORD PTR imgFloatRes$1$[rsp]
	call	_aligned_free

; 204  : 
; 205  : 	ret = ilSetData(imgData);

	mov	rcx, QWORD PTR imgData$1$[rsp]
	call	QWORD PTR __imp_ilSetData

; 206  : 	ilEnable(IL_FILE_OVERWRITE);

	mov	ecx, 1568				; 00000620H
	call	QWORD PTR __imp_ilEnable

; 207  :     //ilSaveImage((const char*)("output.jpg"));
; 208  :     ilSaveImage((const char*)("output.bmp"));				// teszteléshez

	lea	rcx, OFFSET FLAT:??_C@_0L@OICGFOEL@output?4bmp?$AA@
	call	QWORD PTR __imp_ilSaveImage

; 209  : 	ilDeleteImages(1, &ilImg);

	lea	rdx, QWORD PTR ilImg$[rsp]
	mov	ecx, 1
	call	QWORD PTR __imp_ilDeleteImages

; 210  : 
; 211  : 	verifyImage();

	call	?verifyImage@@YAHXZ			; verifyImage

; 212  : 
; 213  : #endif
; 214  : }

	mov	r14, QWORD PTR [rsp+392]
	xor	eax, eax
	mov	r13, QWORD PTR [rsp+384]
	mov	rcx, QWORD PTR __$ArrayPad$[rsp]
	xor	rcx, rsp
	call	__security_check_cookie
	mov	rbx, QWORD PTR [rsp+400]
	add	rsp, 336				; 00000150H
	pop	r15
	pop	r12
	pop	rdi
	pop	rsi
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
END
